---
title: "Bee_Analysis"
output: html_document
date: "2024-11-21"
---

```{r setup, include=FALSE}
library(lubridate)
library(tidyverse)
library(sp)
library(sf)
library(raster)
library(prism)
library(terra)
library(lme4)
library(lmerTest)
library(car)
library(ggplot2)
library(ggeffects)
library(ggpubr)
setwd("~/Bee-Urbanization-BI410")

complete_bee_data <- read_rds("Data/final_bee_dataset")
```

## Adding urbanization levels 

```{r}
head(complete_bee_data)
# using quantile function and POP20
  # if in quantile 1, give it a number 1
  # if in quantile 2, assign it to number 2 etc 
assign_urbanization_level <- function(data){
  
  # initialize a list
  urbanization_level <- list(nrow(data))

  quantile_1 <- quantile(data$POP20, na.rm = TRUE)[1]
  quantile_2 <- quantile(data$POP20, na.rm = TRUE)[2]
  quantile_3 <- quantile(data$POP20, na.rm = TRUE)[3]
  quantile_4 <- quantile(data$POP20, na.rm = TRUE)[4]
  quantile_5 <- quantile(data$POP20, na.rm = TRUE)[5]
  
  for (i in 1:nrow(data)){
    if (quantile_1 <= (complete_bee_data$POP20[i]) && (complete_bee_data$POP20[i]) <= quantile_2){
      append(urbanization_level, 1)
    }
    else if (quantile_2 < (complete_bee_data$POP20[i]) && (complete_bee_data$POP20[i]) <= quantile_3){
      append(urbanization_level, 2)
    }
    else if (quantile_3 < (complete_bee_data$POP20[i]) && (complete_bee_data$POP20[i]) <= quantile_4){
      append(urbanization_level, 3)
    }
    else if (quantile_4 < (complete_bee_data$POP20[i]) && (complete_bee_data$POP20[i]) <= quantile_5){
      append(urbanization_level, 4)
    }
}
}

  # splitting POP20 into 4 even categories
complete_bee_data <- complete_bee_data %>%
  mutate(urbanization_level = sapply(complete_bee_data$POP20, quantile(complete_bee_data$POP20, na.rm = TRUE))) 

assign_urbanization_level <- function(data) {
  quantiles <- quantile(data$POP20, probs = seq(0 , 1, 0.25), na.rm = TRUE)
  
  data <- data %>% 
    mutate(urbanization_level = cut(POP20,
                                    breaks = quantiles,
                                    labels = c("rural", "subrural", "suburban", "urban"),
                                    include.lowest = TRUE))
  
  return(data)
}


complete_bee_data <- assign_urbanization_level(complete_bee_data)

```

## 

```{r}
complete_bee_data <- complete_bee_data %>%
  rowwise() %>%
  mutate(springTemp = mean(c_across(c("tmean_6", "tmean_7", 
                                      "tmean_8", "tmean_9", "tmean_10")), na.rm = TRUE)) %>%
  ungroup()

dat <- data.frame(
  DOY = complete_bee_data$DOY,
  springTemp = scale(complete_bee_data$springTemp),
  urbanizationLevel = complete_bee_data$urbanization_level,
  species = complete_bee_data$Species,
  pop = scale(complete_bee_data$POP20)
)
na.omit(dat)
sum(is.na(dat))
dat$springTemp <- as.numeric(dat$springTemp)



formula <- DOY ~ 1 + urbanizationLevel + springTemp + pop + (1 | species)

model1 <- lmer(formula, data = dat)

summary(model1)
step(model1)

vif(model1)

```




```{r}
# MOdel applied to each species 

select_species <- c("vosnesenskii", "melanopygus", "mixtus", "griseocollis")

model_results <- list()

for (i in seq_along(select_species)) {
  
  formula_for_species <- DOY ~ 1 + urbanization_level + scale(springTemp) + scale(POP20) + (1 | COUNTY)
  
  single_species <- na.omit(complete_bee_data[complete_bee_data$Species == select_species[i], ])
  
  species_model <- lmer(formula_for_species, data = single_species)
  model_results[[select_species[i]]] <- species_model
}

model_summaries <- lapply(model_results, summary)

model_summaries[1]
model_summaries[2]
model_summaries[3]
model_summaries[4]

```


Spring Temperature vs DOY Visualization
``` {r}

#plot(model1)

#ggplot(data = complete_bee_data, aes(x = scale(springTemp), y = DOY)) + geom_point()

tempDOY <- ggpredict(model1, terms = c("springTemp"))

tempDOY_plot <- ggplot(tempDOY, aes(x = x, y = predicted)) +
  geom_point(data = complete_bee_data, 
             aes(x = scale(springTemp), y = DOY, color = "Observed Data"), 
             alpha = 0.5) +
  geom_line(aes(color = "Model Prediction"), linewidth = 1) +
  geom_ribbon(aes(ymin = conf.low, ymax = conf.high), alpha = 0.2) +
  scale_color_manual(values = c("Observed Data" = "steelblue", "Model Prediction" = "darkblue")) +
  labs(x = "Scaled Spring Temperature", y = "DOY", color = "Legend", fill = "Legend") +
  theme_minimal()



tempDOY_plot

```
Urbanization Level vs DOY Visualization
```{r}


urbanizationDOY <- ggpredict(model1, terms = c("urbanizationLevel"))

pvalues_df <- data.frame(
  group1 = "rural",
  group2 = "urban",
  p = "***"
)

urbanizationDOY_plot <- ggplot(urbanizationDOY, aes(x = x, y = predicted)) +
  geom_line(aes(group = 1), size = 1) + 
  geom_errorbar(aes(ymin = conf.low, ymax = conf.high), 
                width = 0.2, size = 0.8, color = "darkgrey") +
  labs(x = "Urbanization Level", 
       y = "Predicted DOY") +
  theme_minimal() +
  stat_pvalue_manual(data = pvalues_df, 
                     label = "p", 
                     y.position = 203, 
                     tip.length = 0.03, 
                     inherit.aes = FALSE, 
                     bracket.size = 0.5,
                     label.size = 5) 


urbanizationDOY_plot

```




Population vs DOY
```{r}
#Not a very helpful graph just made it to look at what it would look like

popDOY <- ggpredict(model1, terms = c("pop"))

popDOY_plot <- ggplot(popDOY, aes(x = x, y = predicted)) +
  geom_point(data = complete_bee_data, 
             aes(x = scale(POP20), y = DOY, color = "Observed Data"), 
             alpha = 0.5) +
  geom_line(aes(color = "Model Prediction"), linewidth = 1) +
  geom_ribbon(aes(ymin = conf.low, ymax = conf.high), alpha = 0.2) +
  scale_color_manual(values = c("Observed Data" = "steelblue", "Model Prediction" = "darkblue")) +
  labs(x = "Scaled Population", y = "DOY", color = "Legend", fill = "Legend") +
  theme_minimal()



popDOY_plot

```
