---
title: "Bee_Urbanization_Project"
output: html_document
date: "2024-11-07"
---

## Data Exploration


``` {r}
#install.packages("lubridate")\
library(lubridate)
library(tidyverse)
library(sp)
library(sf)
library(raster)
library(prism)
library(terra)
setwd("~/Bee-Urbanization-BI410")

bee_data <- read.csv("OBA_2018-2023_combined_dataset_working.csv")

head(bee_data)
#colnames(bee_data)
#unique(bee_data$Species)

#vosenesenskii <- bee_data[bee_data$Species == "vosnesenskii", ]
#melanopygus <- bee_data[bee_data$Species == "melanopygus",]
#griseocollis <- bee_data[bee_data$Species == "griseocollis", ]

# want to just keep our species from the main dataframe
filtered_bee_data <- bee_data[bee_data$Species %in% c("vosnesenskii", "melanopygus", "mixtus", "griseocollis"), ]
colnames(filtered_bee_data)

# want to keep Dec..Lat. and Dec..Long. and Collection.Date and Collection.Day.1
# https://stackoverflow.com/questions/50990412/select-remove-columns-under-conditions-in-dplyr-filter-columns-r
filtered_bee_data <- filtered_bee_data %>%
    dplyr::select(Dec..Lat., Dec..Long., Collection.Date, Species, Year.1)
 
head(filtered_bee_data)

# exploring what rows have na values 
#rows_with_na <- rowSums(is.na(filtered_bee_data)) > 0
# Display rows with NA
#filtered_bee_data[rows_with_na, ]

# removing these na rows 
filtered_bee_data <- na.omit(filtered_bee_data)
```

# creating a day of year column
```{r}
# logic behind the day of year: January 1st is day 1, jan 2nd is day 2 etc 

  # using lubridate

calc_day_of_year <- function(date){
  
  # converting the string object to a Date object
  # parses mm/dd/yyyy
  date <- mdy(date) 
  
  # get day of year
  day_of_year <- yday(date)
  
  return (day_of_year)
  
}

filtered_bee_data <- mutate(filtered_bee_data, DOY = calc_day_of_year(Collection.Date))

#rows_with_na <- rowSums(is.na(filtered_bee_data)) > 0
#filtered_bee_data[rows_with_na, ]
# row 8791 has Collection.Date of 2018--20
  # dropping this row 
# row 18851 had Collection.Date of 2019-6-31, this day doesn't exist allegedly there are only 30 days in june
# the rest of the rows without a DOY value don't have a Collection.Date date

#dropping all days missing a DOy value? Which is ~740 values 

month <- seq(as.Date("2020-01-01"), 
             as.Date("2020-12-01"), 
             by = "1 month")
month_label <- lubridate::month(month, label = TRUE)

winter.months <- seq(as.Date("2020-09-01"), 
                     as.Date("2021-08-01"), 
                     by = "1 month")
winter.month_label <- lubridate::month(winter.months, label = TRUE)

filtered_bee_data <- filtered_bee_data %>%
  mutate(Collection.Date=mdy(Collection.Date)
         ,year=as.numeric(year(Collection.Date))
         ,month=month(Collection.Date)
         ,doy = yday(Collection.Date)
  ) %>%
  arrange(year,doy) 

filtered_bee_data <- filtered_bee_data %>% rename(latitude = Dec..Lat., longitude = Dec..Long.)

filtered_bee_data <- mutate(filtered_bee_data,
                 winter.year = ifelse(month>8, year+1, year)
                 ,winter.month = ifelse(month>8, month-8, month+4)
                 ,winter.day = ifelse(month>8, doy-243, doy+120)
)



filtered_bee_data <- na.omit(filtered_bee_data)

dim(filtered_bee_data)

```


```{r}
#Adding PRISM Data 

prism_set_dl_dir("prism_data")

# get_prism_monthlys(
#   type = "tmean", 
#   year=2016:2021,
#   mon=1:12,
#   keepZip = FALSE
# )

sub.tmean <- prism_archive_subset("tmean", "monthly", mon = 1:12)

RS <- pd_stack(sub.tmean) ##raster file   # (prism_stack and ls_prism_data deprecated)

bee.test <- filtered_bee_data
bee.spdf <-   SpatialPointsDataFrame(coords=bee.test[,c('longitude','latitude')], 
                                    data=bee.test, proj4string = CRS("+proj=longlat +ellps=WGS84 +no_defs"))

bee.clim <- extract(RS, bee.spdf,  fun=mean, na.rm=TRUE, sp=TRUE) 
bee.clim <- as.data.frame(bee.clim)
head(bee.clim,2); dim(bee.clim)


bee_long <- pivot_longer(bee.clim, cols=starts_with("PRISM")) %>%
  separate(col=name, sep="_", into=c("r1","var","class","res","dd","r2")) %>%
  mutate(year.prism=as.numeric(str_sub(dd, 1, 4)),
         month.prism=as.numeric(str_sub(dd, 5, 6)))%>%
  dplyr::select(-c(r1,r2,latitude.1, longitude.1, dd))
print(bee_long)
dim(bee_long)

bee_long <- bee_long %>%  
  mutate(winter.year.prism = ifelse(month.prism>8, year.prism+1, year.prism)
         ,winter.month.prism = ifelse(month.prism>8, month.prism-8, month.prism+4)
         ,tmean.month = paste(var, winter.month.prism, sep="_")
  ) %>% filter(winter.year.prism == winter.year) # filter to only the prism data from the same winter-year as the observation
print(bee_long)
dim(bee_long)

bee_long <- bee_long %>% 
  dplyr::select(-c(month.prism,winter.month.prism, year.prism,class))%>% 
  print(bee_long)

bee_long <- bee_long %>%
  group_by(Species, winter.year.prism, tmean.month) %>%
  mutate(row_id = row_number()) # Add a unique ID to prevent collapsing


bee.dat.tmean <- pivot_wider(
  bee_long,
  names_from = tmean.month,
  values_from = value,
  values_fn = mean # Or another aggregation function
)

# pivot back to wide
#bee.dat.tmean <- pivot_wider(bee_long, names_from=tmean.month, values_from=value, values_fn = mean) %>% dplyr::select(-c(var))
print(bee.dat.tmean)
dim(bee.dat.tmean)

bee.data <- bee.dat.tmean
print(bee.data)

bee_data_wTemp <-  bee.data %>%
  rowwise()%>%
  mutate(temp=mean(c_across(tmean_1:tmean_9))) %>% dplyr::select(-c(var, Year.1))

dim(bee_long) # Check the size of the dataset before pivoting
summary(bee_long) # Summarize to check for NAs
anyDuplicated(bee_long[, c("Species", "winter.year.prism", "tmean.month")]) # Check for duplicates in key columns

sum(is.na(bee_data_wTemp)) 
dim(bee_data_wTemp)
dim(filtered_bee_data) #large difference in row numbers, why? 

dim(filtered_bee_data)
dim(bee.spdf)
dim(bee.clim)
dim(bee_long)
dim(bee.dat.tmean)
dim(bee_data_wTemp)


```


```{r}

census <- read.csv("CensusBlockGroups.csv")

census_shp <- st_read("Data/CensusBlockGroups/CensusBlockGroups.shp")

census_sf <- census_shp %>% 
  st_transform(crs = "EPSG:4326") %>% 
  rename(latitude = INTPTLAT, longitude = INTPTLON) %>% 
  dplyr::select(latitude, longitude, geometry, POP20, POPDENS20, COUNTY)
  

bee_sf <- st_as_sf(bee_data_wTemp,
                        coords = c("longitude", "latitude"),
                        crs = crs("EPSG:4326"))
census_sf <- st_cast(census_sf, "POLYGON")

bee_with_census <- st_join(bee_sf, census_sf)
dim(bee_with_census)

saveRDS(bee_with_census, "Data/final_bee_dataset")
# want to keep columns INTPTLAT, INTPTLON, COUNTY?, NAME?, POP20


```