---
title: "Bee Oregon Map Figure"
output: html_document
date: "2024-11-26"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(dplyr)
library(ggplot2)
library(terra)
library(sf)
library(tidyverse)

```

```{r Bombus observations across oregon}
complete_bee_data <- read_rds("Data/complete_bee_data")

# making our data into a shapefile for plotting
bombus_shp <- st_as_sf(complete_bee_data,
                                   coords = c("Dec..Long.", "Dec..Lat."),
                                   crs = st_crs("EPSG:4326"), na.fail = FALSE	
)

# downloading in the Oregon base map 
or <- map_data("county", "oregon")%>% 
  dplyr::select(lon = long, lat, group, id = subregion)

# first need to create the extent from the or dataframe
min_long <- min(or$lon)
max_long <- max(or$lon)
min_lat <- min(or$lat)
max_lat <- max(or$lat)

or_extent <- c(xmin = min_long, xmax = max_long, ymin = min_lat, ymax = max_lat)

# create bounding box
bbox <- st_bbox(or_extent, crs = st_crs(bombus_shp))
# concert bbox to sf polygon
bbox_poly <- st_as_sfc(bbox)
# crop shapefile using bounding box
cropped_bombus_shp <- st_intersection(bombus_shp, bbox_poly)


# plotting!
ggplot() +
  geom_polygon(data=or, aes(x=lon, y=lat, group=group)) +
  geom_sf(data = cropped_bombus_shp, aes(color = Species)) +
  scale_color_viridis_d(name = "Species") + 
  ggtitle("Bombus Species Observations Across Oregon") + 
  labs(x = "longitude", y = "latitude") + 
  scale_color_manual(
    values = c("red", "white", "forestgreen", "violet"), # Custom colors for each species
    name = "Species"
  ) 
```

```{r Census Blocks Plot}

census_shp <- st_read("Data/CensusBlockGroups/CensusBlockGroups.shp")
census_csv <- read.csv("CensusBlockGroups.csv")

ggplot() +
  geom_polygon(data=or, aes(x=lon, y=lat, group=group), fill = "tan")

census_shp <- census_shp %>%
  mutate(pop_bin = cut(POP20, breaks = c(0, 3000, 4000,5000, 6000, Inf),
                       labels = c("0-3k", "3k-4k","4k-5k", "5k-6k", "6k+"),
                       include.lowest = TRUE))

ggplot() +
   # census block layer
  #geom_sf(data = census_shp, aes(fill = COUNTY)) + 
  geom_sf(data = census_shp, aes(fill = POP20)) + 
  scale_fill_gradient(low="beige", high = "brown", name = "Population by Census Block") + 
  
  geom_sf(data = complete_bee_data, aes(color = springTemp)) +
  scale_color_gradient(low="blue", high="red", name = "Avg Spring Temp °C (Feb-June)") + ggtitle("All Bee Locations with Census Blocks and Spring Temperature Info") + theme(plot.title = element_text(hjust = 0.3, vjust = 3)) + 
  
  xlab("lon") + ylab("lat") 

  


```
```{r climate plot}


# Calculating the same average spring temperatures that we used for the model 
complete_bee_data <- cropped_bombus_shp %>%
  rowwise() %>%
  mutate(springTemp = mean(c_across(c("tmean_6", "tmean_7", 
                                      "tmean_8", "tmean_9", "tmean_10")), na.rm = TRUE)) %>%
  ungroup()

# Plotting the average spring temperatures where the bees were captured, and outlining the counties
                            # and we can see generally where the populated areas are
ggplot() +
  geom_polygon(data=or, aes(x=lon, y=lat, group=group), color = "black", fill = "tan")+
  geom_sf(data = complete_bee_data, aes(color = springTemp)) +
  scale_color_gradient2(low = "white", 
    mid = "blue", 
    high = "red", 
    midpoint = .02, name = "Temperature (°C)" ) + ggtitle("Average Spring (Feb-June) Temperatures (°C)") + theme(plot.title = element_text(hjust = 0.5)) + xlab("Longitude") + ylab("Latitude")



```
